import type { Therapist, Review } from './types';

export const therapists: Therapist[] = [
  {
    id: '1',
    userId: 'usr_doc_1',
    name: 'Dr. Priya Sharma',
    title: 'Speech-Language Pathologist',
    specializations: ['Speech Therapy'],
    experience: 12,
    rating: 4.9,
    reviewCount: 287,
    fee: 800,
    city: 'Bangalore',
    state: 'Karnataka',
    languages: ['English', 'Hindi', 'Kannada'],
    mode: 'both',
    bio: 'Dr. Priya Sharma is a certified Speech-Language Pathologist with 12 years of experience working with patients of all ages — from toddlers to seniors. She specialises in articulation disorders, language delays, stuttering, voice disorders, and post-stroke speech rehabilitation. Her empathetic, evidence-based approach ensures effective outcomes for every patient.',
    qualifications: ['M.Sc. Speech-Language Pathology, AIIMS Delhi', 'RCI Certified (CRR No. 12345)', 'ASHA Certified Member', 'Certificate in AAC (Augmentative and Alternative Communication)'],
    registrationNo: 'RCI-12345',
    nextAvailable: 'Today, 4:00 PM',
    verified: true,
    featured: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya&backgroundColor=b6e3f4',
    conditions: ['Stuttering', 'Articulation Disorders', 'Language Delay', 'Voice Disorders', 'Post-Stroke Aphasia', 'Autism Spectrum Disorder'],
    ageGroups: ['Children (2–12)', 'Teens (13–17)', 'Adults (18–60)', 'Seniors (60+)'],
    sessionDuration: 45,
  },
  {
    id: '2',
    name: 'Dr. Rahul Mehta',
    title: 'Clinical Psychologist',
    specializations: ['Psychology', 'Behavioral Therapy'],
    experience: 8,
    rating: 4.8,
    reviewCount: 154,
    fee: 1200,
    city: 'Mumbai',
    state: 'Maharashtra',
    languages: ['English', 'Hindi', 'Marathi', 'Gujarati'],
    mode: 'both',
    bio: 'Dr. Rahul Mehta is a Clinical Psychologist with expertise in mental health challenges across all age groups. He treats anxiety, depression, OCD, trauma, and relationship issues in adults, as well as ADHD and behavioural challenges in younger patients. His approach combines CBT, mindfulness, and solution-focused therapy.',
    qualifications: ['PhD Clinical Psychology, University of Mumbai', 'M.Phil Child Psychology, NIMHANS', 'RCI Certified', 'CBT Certified Practitioner'],
    registrationNo: 'RCI-23456',
    nextAvailable: 'Tomorrow, 10:00 AM',
    verified: true,
    featured: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rahul&backgroundColor=c0aede',
    conditions: ['Anxiety & Depression', 'OCD', 'PTSD / Trauma', 'ADHD', 'Relationship Issues', 'Stress Management'],
    ageGroups: ['Teens (13–17)', 'Adults (18–60)', 'Seniors (60+)'],
    sessionDuration: 60,
  },
  {
    id: '3',
    name: 'Dr. Ananya Krishnan',
    title: 'Occupational Therapist',
    specializations: ['Occupational Therapy'],
    experience: 6,
    rating: 4.7,
    reviewCount: 98,
    fee: 700,
    city: 'Chennai',
    state: 'Tamil Nadu',
    languages: ['English', 'Tamil', 'Hindi'],
    mode: 'both',
    bio: 'Dr. Ananya Krishnan is a skilled Occupational Therapist helping people of all ages regain independence in daily life. She works with children on developmental skills and with adults recovering from injury, stroke, or managing chronic conditions — helping them return to work and everyday activities.',
    qualifications: ['B.Sc. Occupational Therapy, CMC Vellore', 'M.Sc. Paediatric Occupational Therapy, UK', 'Sensory Integration Certified', 'Hand Therapy Certified'],
    registrationNo: 'OT-34567',
    nextAvailable: 'Today, 6:00 PM',
    verified: true,
    featured: false,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ananya&backgroundColor=ffdfbf',
    conditions: ['Post-Stroke Rehabilitation', 'Sensory Processing Disorder', 'Fine Motor Delays', 'Work Injury Recovery', 'Arthritis Management', 'Hand & Upper Limb Rehab'],
    ageGroups: ['Children (2–12)', 'Teens (13–17)', 'Adults (18–60)', 'Seniors (60+)'],
    sessionDuration: 45,
  },
  {
    id: '4',
    name: 'Dr. Vikram Nair',
    title: 'Audiologist & Speech Therapist',
    specializations: ['Audiology', 'Speech Therapy'],
    experience: 15,
    rating: 4.9,
    reviewCount: 312,
    fee: 900,
    city: 'Hyderabad',
    state: 'Telangana',
    languages: ['English', 'Hindi', 'Telugu'],
    mode: 'in-clinic',
    bio: 'Dr. Vikram Nair combines expertise in audiology and speech therapy to deliver comprehensive hearing and communication care. He treats patients of all ages — from newborns with hearing screening to adults with tinnitus and age-related hearing loss — and specialises in cochlear implant rehabilitation.',
    qualifications: ['M.Sc. Audiology & Speech-Language Pathology, Manipal', 'PhD Audiology, AIIMS', 'Cochlear Implant Rehabilitation Certified', 'Pediatric & Adult Audiology Specialist'],
    registrationNo: 'RCI-45678',
    nextAvailable: 'Wed, 11:00 AM',
    verified: true,
    featured: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=vikram&backgroundColor=d1f4e0',
    conditions: ['Hearing Loss', 'Tinnitus', 'Cochlear Implant Rehab', 'Auditory Processing Disorder', 'Age-Related Hearing Loss', 'Speech Delay due to Hearing Loss'],
    ageGroups: ['Children (2–12)', 'Teens (13–17)', 'Adults (18–60)', 'Seniors (60+)'],
    sessionDuration: 60,
  },
  {
    id: '5',
    name: 'Dr. Sneha Patel',
    title: 'Rehabilitation Specialist',
    specializations: ['Physiotherapy', 'Occupational Therapy'],
    experience: 10,
    rating: 4.8,
    reviewCount: 201,
    fee: 1000,
    city: 'Ahmedabad',
    state: 'Gujarat',
    languages: ['English', 'Hindi', 'Gujarati'],
    mode: 'both',
    bio: 'Dr. Sneha Patel is a Rehabilitation Specialist focusing on neurological and musculoskeletal recovery. She works with stroke survivors, patients with Parkinson\'s disease, and those recovering from orthopaedic surgeries. Her goal-oriented approach helps patients restore maximum independence.',
    qualifications: ['MPT Neurology, B.J. Medical College', 'BPT, SVNIT', 'Bobath Certified', 'NDT Certified Therapist'],
    registrationNo: 'PT-56789',
    nextAvailable: 'Tomorrow, 2:00 PM',
    verified: true,
    featured: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sneha&backgroundColor=ffd5e5',
    conditions: ['Stroke Rehabilitation', 'Parkinson\'s Disease', 'Knee / Hip Replacement Recovery', 'Spinal Cord Injury', 'Multiple Sclerosis', 'Cerebral Palsy'],
    ageGroups: ['Adults (18–60)', 'Seniors (60+)'],
    sessionDuration: 60,
  },
  {
    id: '6',
    name: 'Dr. Arjun Das',
    title: 'Physiotherapist',
    specializations: ['Physiotherapy'],
    experience: 7,
    rating: 4.6,
    reviewCount: 87,
    fee: 600,
    city: 'Kolkata',
    state: 'West Bengal',
    languages: ['English', 'Hindi', 'Bengali'],
    mode: 'both',
    bio: 'Dr. Arjun Das is a Sports & Orthopaedic Physiotherapist helping patients of all ages recover from injuries and manage chronic pain. Whether you are an athlete bouncing back from a sports injury or a senior dealing with joint pain, he designs personalised rehabilitation plans.',
    qualifications: ['BPT, University of Calcutta', 'MPT Orthopaedics, NIMHANS', 'Sports Physiotherapy Certified', 'Kinesio Taping Certified'],
    registrationNo: 'PT-67890',
    nextAvailable: 'Today, 5:30 PM',
    verified: true,
    featured: false,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=arjun&backgroundColor=b9e5e8',
    conditions: ['Sports Injuries', 'Chronic Back Pain', 'Neck & Shoulder Pain', 'Post-Surgery Rehab', 'Arthritis', 'Sciatica'],
    ageGroups: ['Teens (13–17)', 'Adults (18–60)', 'Seniors (60+)'],
    sessionDuration: 45,
  },
  {
    id: '7',
    name: 'Dr. Meera Iyer',
    title: 'Special Educator & Learning Specialist',
    specializations: ['Special Education'],
    experience: 9,
    rating: 4.9,
    reviewCount: 143,
    fee: 500,
    city: 'Pune',
    state: 'Maharashtra',
    languages: ['English', 'Hindi', 'Marathi'],
    mode: 'both',
    bio: 'Dr. Meera Iyer is a certified Special Educator and Learning Specialist working with school-age children, teens, and young adults. She creates personalised learning programmes for dyslexia, dyscalculia, learning disabilities, and supports students preparing for board exams and college.',
    qualifications: ['M.Ed Special Education, Pune University', 'RCI Certified Special Educator', 'Dyslexia Association of India Certified', 'Applied Behavior Analysis Certified'],
    registrationNo: 'SE-78901',
    nextAvailable: 'Tomorrow, 9:00 AM',
    verified: true,
    featured: false,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=meera&backgroundColor=e8d5b7',
    conditions: ['Dyslexia', 'Dyscalculia', 'Intellectual Disability', 'Learning Disabilities', 'ADHD (Academic Support)', 'Exam Anxiety'],
    ageGroups: ['Children (2–12)', 'Teens (13–17)', 'Adults (18–60)'],
    sessionDuration: 45,
  },
  {
    id: '8',
    name: 'Dr. Kavya Reddy',
    title: 'Speech-Language Pathologist',
    specializations: ['Speech Therapy'],
    experience: 5,
    rating: 4.7,
    reviewCount: 76,
    fee: 650,
    city: 'Hyderabad',
    state: 'Telangana',
    languages: ['English', 'Telugu', 'Hindi'],
    mode: 'online',
    bio: 'Dr. Kavya Reddy is a dedicated Speech-Language Pathologist offering online therapy for patients across India. She works with adults recovering from stroke or brain injury, professionals wanting to improve their communication and accent, and individuals with voice disorders.',
    qualifications: ['M.Sc. Speech-Language Pathology, Osmania University', 'RCI Certified', 'Voice Therapy Specialist', 'PROMPT Trained'],
    registrationNo: 'RCI-89012',
    nextAvailable: 'Today, 7:00 PM',
    verified: true,
    featured: false,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=kavya&backgroundColor=c9e8d5',
    conditions: ['Post-Stroke Aphasia', 'Voice Disorders', 'Accent Modification', 'Professional Communication', 'Fluency Disorders', 'Selective Mutism'],
    ageGroups: ['Teens (13–17)', 'Adults (18–60)', 'Seniors (60+)'],
    sessionDuration: 30,
  },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    therapistId: '1',
    patientName: 'Ravi K.',
    rating: 5,
    comment: 'I had a stroke 8 months ago and struggled to speak clearly. After working with Dr. Priya for 4 months, my speech has improved dramatically. She is incredibly patient and professional.',
    date: '2024-01-15',
    verified: true,
    condition: 'Post-Stroke Aphasia',
  },
  {
    id: 'r2',
    therapistId: '1',
    patientName: 'Sunita M.',
    rating: 5,
    comment: 'Dr. Priya helped my teenage son with his stuttering. The progress has been remarkable and his confidence has grown so much. Highly recommend her to anyone.',
    date: '2024-01-08',
    verified: true,
    condition: 'Stuttering',
  },
  {
    id: 'r3',
    therapistId: '2',
    patientName: 'Amit P.',
    rating: 5,
    comment: 'I was dealing with severe anxiety and work stress. Dr. Rahul\'s CBT sessions gave me practical tools I use every day. He is compassionate and non-judgemental.',
    date: '2024-01-20',
    verified: true,
    condition: 'Anxiety',
  },
];

export const specializations = [
  { name: 'Speech Therapy', icon: '🗣️', color: 'bg-brand-50 text-brand-700 border-brand-200', count: 48 },
  { name: 'Psychology', icon: '🧠', color: 'bg-purple-50 text-purple-700 border-purple-200', count: 32 },
  { name: 'Occupational Therapy', icon: '🤲', color: 'bg-coral-50 text-coral-700 border-coral-200', count: 27 },
  { name: 'Behavioral Therapy', icon: '💡', color: 'bg-yellow-50 text-yellow-700 border-yellow-200', count: 21 },
  { name: 'Physiotherapy', icon: '🏃', color: 'bg-green-50 text-green-700 border-green-200', count: 19 },
  { name: 'Audiology', icon: '👂', color: 'bg-blue-50 text-blue-700 border-blue-200', count: 15 },
  { name: 'Special Education', icon: '📚', color: 'bg-pink-50 text-pink-700 border-pink-200', count: 34 },
  { name: 'Child Development', icon: '👶', color: 'bg-orange-50 text-orange-700 border-orange-200', count: 22 },
];

export const cities = ['All Cities', 'Bangalore', 'Mumbai', 'Chennai', 'Hyderabad', 'Delhi', 'Pune', 'Kolkata', 'Ahmedabad'];
